### ISSUE TITLE
x86 randomly crashing without exception

### ISSUE THREAD

**Issue by philipneill** [DiagProf/ISO22900.II#2]
Hello Jörg,

i need to compile in x86 and then this happens with the SimpleSendAndReceive example (only changes: put the right request and rx/tx ID for the ECU in and threw the delay out):
![image](https://user-images.githubusercontent.com/95969148/164470533-3c143cdd-8c1e-4cc7-b8f6-2a516ffd1b9c.png)

So its just crashing after about 15 seconds, but without throwing any exception or halting the debugger...
Do you have any clou what could be the issue here?

Best Reagrds,

Philip

**Comment by DiagProf** [comment]
Hello Philip,
you use a KTM CCU with the VCI1000. And this D-PDU-API writes to the standard output (in this case the console).
And now anything can happen.
Ask the D-PDU-API manufacturer how you can switch off the behavior.

I don't want to provide any support for the various D-PDU-API manufacturers from my repository here.
And your questions, first about Vector and now about this case, go in that direction. So please avoid.

Best Reagrds,

Jörg

**Comment by philipneill** [comment]
I don’t want any API Support, but I got the behaviour with the Vector API and the AVL API, and both only with the x86 compile, so I think it’s reasonable to guess the issue must be in the Wrapper.
But I will have further looks into it, unfortunately I don’t get any exceptions, so there’s no real starting point.

Nevertheless thank you for your response!

**Comment by philipneill** [comment]
Thanks to a good hint from Jörg i finally found the issue. :)

The problem was the D-PDU-API randomly sending things to the stdout (the Console), which then inteferred with the AnsiConsole, causing the issues. As suggested, turning off the Debug behaviour solved the issue and is running stable since!
The wrapper alone sends only the can messages to the console, all other messages come from the API itself. I wasnt aware of this and thought that an API itself isnt sending things to the stdout.

So thank you Jörg, not only for the good project but also for your support!
