### ISSUE TITLE
DoIP handling between a D-PDU API VCI Interface and the Diagnostic Computer.

### ISSUE THREAD

**Issue by brainbubblersbest** [DiagProf/ISO22900.II#5]
Hello, you already explained a lot over the DoIP handling between the VCI and the Ethernet based Vehicle. And I find that very informative.

Can you say a few words about the Communication between VCI and the Windows Diagnostic PC?

It's hard to get this down to a easier Explanation because it's hard to find Informations for that.

For example: Bosch 6516 or ETAS 6515 or Teradyne I-View Interfaces came all with Software for J2534Passtrough Mode OR with a Software Handler for a D-PDU API configuration.
The D-PDU API configuration can be made over: 
1: A usb NDIS Connection 
2: A LAN Connection
3: A WLAN Connection

From my understanding, these are all tcp/udp Connections. 
The Question here:
What in Detail does the Configuration Software create on the Host Computer (DLL Librarys, IP Routes, whatever) matching the D-PDU Standard. That Routes a connection over that point to point or infrastructure LAN over to the VCI?

What Files on the PC are involved into that?
What files need to exist that the diagnostic Software can basically  "see" the interface in the LAN/WAN.

Is the vendor API configuration tool directly involved?
Or does the API configuration Tool create just some Files on the Host Computer?

Does this need a Driver File in */System32/
?

I appreciate your Work.
I have a Bag with a few Dozend Interfaces, the half of them are D-PDU API conform but this is actually useless.

I actually try to get a Bosch/Teradyne I-View Interface to work with Busmaster from the ETAS/RBEI. Maybe you find that Project interesting too? 😉
A Universal D-PDU API support would be great.

https://github.com/rbei-etas/busmaster/issues/35#issue-2112137

And you would maybe get immediate attention from ETAS and RBEI 😄

**Comment by brainbubblersbest** [comment]
`https://www.emotive.de/wiki/index.php?title=Main_Page`

**Comment by DiagProf** [comment]
Hello,
to your question...
>Can you say a few words about the Communication between VCI and the Windows Diagnostic PC?

ISO22900-2 explicitly excludes the description of the connection between PC and VCI.
![PCtoVCI is not a Part](https://user-images.githubusercontent.com/56319388/232138160-580a55cc-b3b9-49b1-a06e-5bc19e3e0e2b.png)

If you want to know more about the PC<-> VCI connection, you have to read the D-PDU-API vendor/manufacturer documentation.

**Comment by brainbubblersbest** [comment]
That detailed Technical Documentation sadly is very Hard to get from Bosch, ETAS, Vector, DSA, Teradyne (sold to Bosch) and all others.

**Comment by DiagProf** [comment]
Because the config tools of the respective manufacturers are also installed during the installation. This is what the tool looks like at Bosch, for example.
![B](https://user-images.githubusercontent.com/56319388/232152062-f87bc3ae-d5f7-4afc-8f4f-b174534b6239.png)

**Comment by brainbubblersbest** [comment]
Yes. Your right. But for example the spx i-view vci isnt supported anymore.
No new driver or config Tools are available. If a Software like Busmaster
wont find it. Even with the old Software from 2013. How should someone get
a Clue, where to start debug without the access to that informations?

Thats only possible for Diagnostic authoring Staff employes in Business
Workplaces.

I like the Open Source mindset as much I like your Work here.

Thank you for your Time.

DiagProf ***@***.***> schrieb am Fr., 14. Apr. 2023, 22:50:

**Comment by DiagProf** [comment]
I understand your pain. Maybe you know a diagnostic software (probably an old one of course) that supports (installs) the i-view VCI driver. From this installation you could perhaps extract the driver installation. 
If that succeeds, it probably fails because of the driver signature that was introduced with win7.

I wish you much success

**Comment by brainbubblersbest** [comment]
My main Question here is: How can a Driver be associated to a device that
is located in the LAN environment?
The interface doesnt have a usb connector.
Which driver Koncept is here in use.
At First I thought about a ndis driver. But this suits here for usb to
ethernet Hardware.
Network Printers have their own driver group too.
That would be a good hint if you have one.

DiagProf ***@***.***> schrieb am Sa., 15. Apr. 2023, 22:01:
